### ISSUE TITLE
garbage text not cleaned up 

### ISSUE THREAD

**Issue by andpor** [apostrophecms/sanitize-html#164]
I have a dirty html string that looks like this:

`"<html><body><p> some text </p></body></html> &%^junkunprintablecharshere"`

This string results from copy in MS outlook sometimes. I would expect sanitizeHtml to drop everything after closing `</html>` but it does not behave this way and I see the garbage chars after `</html>` returned as well. 

Is this by design and are there are ways to ensure clean html in returned i.e. all garbage after `</html>` is truncated when sanitizeHtml returns?

Many thanks.

**Comment by boutell** [comment]
sanitize-html drops tags that are not on its allowed list. It doesn't view the "html" tag as a special case, mainly because we deal primarily with HTML fragments.

I can see why it would be reasonable to ignore any content after the close of an html tag, although for bc we'd want that to be an option. A PR would be welcome.

**Comment by andpor** [comment]
i will give it a shot.. :)

**Comment by andpor** [comment]
@boutell  PR created https://github.com/punkave/sanitize-html/pull/166

**Comment by andpor** [comment]
PR updated.

**Comment by mikesamuel** [comment]
I think this is a duplicate of [issue 149](https://github.com/punkave/sanitize-html/issues/149).

**Comment by andpor** [comment]
Yes it is...
