### ISSUE TITLE
No guidance on where to report security issues

### ISSUE THREAD

**Issue by mikesamuel** [apostrophecms/sanitize-html#170]
https://github.com/punkave/sanitize-html#support says

> ## Support

> Feel free to open issues on github.

There's no way to restrict access to issues on public github repos, so reporting a security vulnerability necessarily means publicly reporting it before a patch has been reviewed and committed.

Your documentation should include a point-of-contact for security-relevant bugs.

Alternatively, ["Creating an issues only repository"](https://help.github.com/articles/creating-an-issues-only-repository/) might be an option.

**Comment by boutell** [comment]
That's a good question. We should also define "security-relevant." My feeling is that since sanitizing HTML is this module's entire job, failures to do that belong in the regular issues of the repo. While something that could somehow permit arbitrary JS code execution would be more "security-relevant." Open to discussion on this point but I would hate to have to go to a more closed process for resolving the primary type of bug this module is likely to have.

**Comment by mikesamuel** [comment]
How about

**Comment by mikesamuel** [comment]
How about recommending alternative disclosure for

* arbitrary code execution with a non-permissive policy as you mentioned
* evasion of a policy whose behavior is clearly documented and that an end-user might plausibly write 

and leaving as bugs any oddities relating to policies whose behavior is not documented?

Btw, I created a [`.github/ISSUE_TEMPLATE.md`](https://github.com/blog/2111-issue-and-pull-request-templates) for one project so that the ["New Issue"](https://github.com/OWASP/java-html-sanitizer/issues/new) link routed reporters to the right place.

**Comment by abea** [comment]
There is now a security policy to cover these needs. Thank you for flagging this. https://github.com/apostrophecms/sanitize-html/security/policy
