### ISSUE TITLE
Strings instead of string arrays in whitelists can lead to unexpected results

### ISSUE THREAD

**Issue by mikesamuel** [apostrophecms/sanitize-html#175]
```js
'<script>alert(1)</script>' ==
sanitizeHtml(
    '<script>alert(1)</script>',
    { allowedTags: 'noscript' });
```
because `sanitizeHtml` internally ends up doing `'noscript'.indexOf('script') !== -1` to determine whether a `<script>` tag is allowed.

This is probably not security-critical.
A policy is unlikely to have just one tag, but one allowed attribute is more likely.

It would be nice if it were harder to write policies with unintended consequences.

Maybe, throw an exception, or wrap strings with arrays when the string is found.

Alternatively, instead of using `.indexOf` internally to check set membership, consistently call out to a function like

```js
function policyWhitelistContains(whitelist, element) {
  if (Array.isArray(whitelist)) {
    return whitelist.indexOf(element) >= 0;
  }
  return element === whitelist;
}
```

**Comment by kedarchandrayan** [comment]
Hello Team,
cc: @boutell 

The issue caused is because `indexOf` works on both String and Array. Looking at the test cases, I think the intended use was with Array. But people might have used it on Strings too.

Should I add an agnostic check as proposed in this thread?

Another approach can be to sanitize the options and turn strings into arrays at the beginning.

Please let me know your opinion. I will be happy to contribute and close this issue.

Thanks,
Kedar Chandrayan

**Comment by boutell** [comment]
The documentation could be more explicit, but nowhere is it suggested that strings are supported for these list arguments, and I don't think we should add weight and impact performance by adding runtime checking of these or adding split calls for strings, etc.

Those who want to can already use the community-maintained TypeScript typings to avoid problems with incorrect option types.

**Comment by kedarchandrayan** [comment]
Agreed! TypeScript typings will help solve the confusion, if any.
