### ISSUE TITLE
Allow for whitelisted "style" properties

### ISSUE THREAD

**Issue by jsumnersmith** [apostrophecms/sanitize-html#30]
Some JS plugins (ckEditor for instance) depend heavily on injected styles, and in a responsive world, that can spell trouble.

Can we try whitelisting selected CSS properties to be allowed through the "style" attribute?

**Comment by danilodeveloper** [comment]
@boutell if someone inject an malicious URL to load a .js the CSP (we should use CSP :smile:) will block. I think this is a good idea. :+1:

**Comment by boutell** [comment]
N-oooo, I don't think we are going to stop exercising control over the
output just because some browsers might, maybe, some of the time, do the
right thing for us (:

Either we have control over what's coming out or we don't do it.

On Fri, Feb 26, 2016 at 10:37 PM, Danilo Barsotti <notifications@github.com>
wrote:

> @boutell <https://github.com/boutell> if someone inject an malicious URL
> to load a .js the CSP (we should use CSP [image: :smile:]) will block. I
> think this is a good idea. [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/30#issuecomment-189571300>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by jcalfee** [comment]
I would not trust the CSP header...   Here have another case though, something simple: `<td style="text-align:right">`  Look like this is important to person in terms of how their language appears.  We may find another work-around for this though.

https://github.com/steemit/steemit.com/issues/30#issuecomment-229032571
