### ISSUE TITLE
sanitizeHtml doesn't render blockquote when used with marked.js

### ISSUE THREAD

**Issue by mellymelon** [apostrophecms/sanitize-html#304]
```
compiledMarkdown(userInput){
  return marked(sanitizeHtml(userInput))
}
```
The output is
&gt; hello world

instead of
> hello world

I inspected and confirmed that the input is &gt; but not `&gt;`

Besides, if I input `<blockquote>hello world</blockquote>`

The output will be

> hello world

which is rendered correctly.

I have no idea why.

Other tags like h1, i, b, table are rendered as expected.

**Comment by boutell** [comment]
sanitize-html sanitizes HTML and returns a valid, equivalent representation of the same HTML. It is not designed to do things like leaving a ">" where the HTML spec says it shouldn't be. It's going to escape that as &lt; which it is doing. This isn't something we could really change, partly because it would allow all sorts of XSRF attacks, but also because we don't control the `htmlparser2` module on top of which sanitize-html is built.
