### ISSUE TITLE
Should not remove the non-html tag

### ISSUE THREAD

**Issue by boyddddd** [apostrophecms/sanitize-html#315]
e.g.
"a <1 and b >2"

after sanitize, we've got "a 2"

I'd expect unchanged content.

What do you think?

**Comment by cmdcolin** [comment]
Also would like to have some option for this :)

**Comment by boutell** [comment]
What you're talking about here is technically a malformed tag, not a rejected tag. That means it's down to the htmlparser2 library to handle it, and I don't think it offers a way to capture the content of malformed tags. Would have to be fixed at a lower level in htmlparser2, in other words, in order to make such an option possible. And then we would certainly escape the < and > to output valid HTML.

**Comment by cmdcolin** [comment]
Was this an option that was recently removed?

I just see e.g. https://github.com/apostrophecms/sanitize-html/commit/a338283a991bbeb0520bc1f8f053c0dce2b2a5d0

https://github.com/apostrophecms/sanitize-html/pull/312/files

**Comment by cmdcolin** [comment]
I guess the cases e.g. in the disallowedTags is slightly different than the OPs case as it might be a malformed tag. In my data I have some weird case where people just actually pass in ```<TRA>``` and except that to be printed so it looks like HTML but is not. Would be curious about escaping disallowed tags and the OPs answer though

**Comment by tstecca** [comment]
Hi all, does anyone have any insight on this? @boyddddd  I have a case similar to @cmdcolin.  We have a proprietary CMS and we use sanitize-html to clean our content.  Some of our content needs to display to the end user as read-able mark-up.  It's always enclosed in a `<code><pre></pre></code>` block.  What's happening is that the content in that <code> block is Java and there are some Java constructs that use a syntax like:  `< XXX >`.  When it goes through sanitize-html all I'm left with it " XXX ". sanitize-html has a discard option that escapes instead of discarding tags. Is there a way to apply this discard option only on certain tags - like my <pre> tag?  Failing that is the are way to ignore a particular tag?  It would be less safe, but as least I wouldn't lose the tags.  Thanks in advance for your help.

**Comment by cmdcolin** [comment]
I had a workaround that basically addresses the problem for my purposes where I had kind of a switch

If the string inputted to my program looked like HTML, I just pass to sanitize-html
Otherwise, if the string I am looking at does not look like HTML, then I just escape angle brackets up front and then pass to sanitize-html just to be sure

I do this by basically using is-html package to test input string, and then if so escape-html npm package to escape it

Logically like this

sanitize-html(isHtml(string)? string : escapeHtml(string))

**Comment by cmdcolin** [comment]
That above solution of course doesn't really allow for a mixing of "non-html" tags with html but it worked for my purpose

**Comment by tstecca** [comment]
cmdcolin, that should actually work in my situation.  I can't believe I didn't think of it.  We already do some processing on the HTML before we send it to sanitize-html.  I can look inside the <pre> tags and escape the < and > characters myself.

**Comment by abea** [comment]
There is [an option to escape disallowed tags](https://github.com/apostrophecms/sanitize-html#choose-what-to-do-with-disallowed-tags), which sounds like it would help resolve this. But @boutell did also note that most of the issue is that this depends on htmlparser2 to do the parsing.
