### ISSUE TITLE
Ignore content in tag

### ISSUE THREAD

**Issue by tstecca** [apostrophecms/sanitize-html#347]
Hello sanitize-html.  Thank you very much for this excellent library.  We use sanitize-html to clean up some content that our company produces. Some of our content is Java Code and needs to display to the end-user as readable Java. In our mark-up it's always enclosed in a `<code class="language-java"><pre>Java code here</pre></code>` block. It's similar to #315. What is happening is that the content in that `<code>` block occasionally contains Java constructs that use a syntax like: < XXX >. When it goes through sanitize-html all I'm left with it " XXX ". I'd like to ignore the `code.language-java` tag. Is the are way to ignore a particular tag? It would be less safe, but as least I wouldn't lose the tags. Thanks in advance for your help.

**Comment by boutell** [comment]
Hi @tstecca, I get what you're trying to do. This library, though, is built on top of htmlparser2 as a parser, so it can only do what that library can do in terms of changing the rules in mid-parse, etc. You might check out the options available for that module, as they can be passed on to it by sanitize-html, but offhand I don't think it can do this one.

Closing because it is out of scope but I wish you good hunting.
