### ISSUE TITLE
Allow dry run to see if there are potential code to be sanitised 

### ISSUE THREAD

**Issue by jessicajacelyn** [apostrophecms/sanitize-html#397]
## The problem to solve

Is your feature request related to a problem you are experiencing that is *not* a bug? Please describe.
It would be nice to be able to detect using a dry run option to see if the HTML is already clean. This can be used for feedback and/or data analytics. The other use case is that the code should not change the original input, the user should be the one to change it, with this feature, we can alert them to update their input.

## Proposed solution

Allow an optional dry run option.

## Alternatives

None found.

**Comment by boutell** [comment]
Hmm. sanitize-html does not modify the string you pass to it, it returns a new string. So on the surface you don't need anything new from us to do this:

```
if (sanitizeHtml(s) === s) {
  // no change
} else {
  // it would change
}
```

However, there's a big catch. There are many ways to write equivalent HTML documents, and sanitize-html doesn't guarantee the representation it returns will be exactly the same. It only guarantees it will have the same meaning.

So if you were to pass in:

```
<h4>5 is > 4</h4>
```

You would get back:

```
<h4>5 is &gt; 4</h4>
```

These two documents are equivalent, but the strings are different, so you would get a false indication of change.

Unfortunately it would be quite hard to change this without taking a very different approach to parsing the markup that would allow us to reconstruct the same representation, not just the same meaning. And we don't have any plans to switch to a different parser library. Plus, we like well-formed output and don't like leaning on browsers to figure out things that really should have been entity-escaped.

But if you're comfortable with what we consider "well-formed" markup, such as always using entity escapes like the one in my example, and want to give feedback on anything that doesn't match that, then you could use an "if" statement like the one I wrote.

Closing because we're not planning to change how we generate our output, but perhaps you'll find the solution of using our formatting as the standard useful for your needs.
