### ISSUE TITLE
Is there a way to disallow an attribute-less span element?

### ISSUE THREAD

**Issue by saveman71** [apostrophecms/sanitize-html#428]
Is there a way to disallow an attribute-less span element?

I don't want to disallow span tags altogether, they are useful when they come with style/class tags. Is there a way to however sanitize them out when they have no attribute, including when the attributes they had were sanitized out by sanitize-html?

**Example:**

```
<p><span><span>Some text</span></span><span></span></p>
```

Would sanitize to:

```
<p>Some text</p>
```

But:

```
<p><span><span class="active">Some text</span></span><span></span></p>
```

Would sanitize to:

```
<p><span class="active">Some text</span></p>
```

And:

```
<p><span style="color: #ccc"><span class="active">Some text</span></span><span></span></p>
```

Would sanitize to:

```
<p><span class="active">Some text</span></p>
```

If the `style` attribute is disallowed.

I'm trying to figure out if this is supported by a combination of current options or if this is a feature request.

**Comment by abea** [comment]
I don't think this is a feature right now. That's probably because `span` is pretty unique from other HTML elements in that it effectively has no inherent styles. A `p`, `div`, or most any other element without any attributes still has stylistic and, for many, semantic value.

I wonder what would happen if you used a `transformTags` function and set the `tagName` to an empty string. It looks like that works from my test! It's a funky hack, but see if that works.

**Comment by Cerberooo** [comment]
I tried 

```javascript
exclusiveFilter: function (frame) {
    // delete pointless spans
    if (frame.tag === 'span' && !Object.keys(frame.attribs).length) {
        return true;
   }
}
```

But unfortunately this discards the text content too.

**Comment by karlhorky** [comment]
> I wonder what would happen if you used a `transformTags` function and set the `tagName` to an empty string

Seems to work for me too! Thanks @Cerberooo !

```js
sanitizeHtml('<div><span>abc</span></div>', {
  transformTags: {
    span() {
      return { tagName: '', attribs: {} };
    },
  },
});
```
