### ISSUE TITLE
When entering text in Input Field, Sanitize-html replace '<' to &lt;

### ISSUE THREAD

**Issue by darshak-gosar** [apostrophecms/sanitize-html#430]
Hi,
When entering text in Input Field, Sanitize-html replace '<' to '&-l-t ; ' and '>' to '&-g-t;'
eg: 
entered: <b> 
displayed: '&-l-t ; ' b '&-g-t ; ' 

Code Snippet:
```
import React, { useState } from "react";
import TextField from "@material-ui/core/TextField";
import sanitizeHtml from "sanitize-html";

export default function BasicTextFields() {
  const [inputValue, updateInputValue] = useState("");

  const updateInputField = (text) => {
    let value = text.currentTarget.value;
    let clean = sanitizeHtml(value, {
      allowedTags: ["b", "i", "em", "strong", "a"]
    });
    updateInputValue(clean);
  };

  return (
    <form">
      <TextField
        id="text"
        color="secondary"
        value={inputValue}
        onChange={(e) => updateInputField(e)}
        inputProps={{
          maxLength: 200
        }}
        characterLimit={200}
      />
      <label>{inputValue}</label>
    </form>
  );
}
```
Is there Something I am missing ?

Thanks,
Darshak Gosar

**Comment by boutell** [comment]
This module sanitizes HTML. Any < and > characters that are not part of tags will be correctly escaped because that is part of sanitizing HTML. But you are trying to feed the input back into the field via a mechanism that probably expects plaintext, not HTML.

You may have better results if you push the contents back into the textarea as raw HTML, but there is no bug here.

**Comment by darshak-gosar** [comment]
Hi @boutell ,
Thanks for the quick response.

**Comment by oller** [comment]
A similar and somewhat related issue (don't want to create another one!):

`before arrow -> after arrow` will get sanitised to `before arrow -&gt; after arrow` as stated above and desired.

However invert the arrow, so it's like an opening tag:

`before arrow <- after arrow` will get sanitised to `before arrow` as it drops everything including and after `<-`.  Which I appreciate it must have deemed a dangerous opening tag.

Besides me parsing the string before sanitising and replacing instances of `<-` and `->` with the respective arrow characters, any other input or advice on how to resolve this would be appreciated @boutell

**Comment by boutell** [comment]
This ticket was closed because the htmlparser2 module, upstream of us, makes these decisions so it's not in our power; and I'm also not sure htmlparser2 is wrong, because it is ambiguous whether these are broken / malicious tags or just plaintext input written by someone who doesn't know they should be writing HTML.

In most of these cases what the developer is really asking for is support for not HTML, but some kind of "plaintext with HTML sprinkled in" format. If you want to support that, it is your responsibility to transform it to compliant HTML before the module sees it.
