### ISSUE TITLE
Question: how to wrap an <img> tag into <a> tag?

### ISSUE THREAD

**Issue by geantas** [apostrophecms/sanitize-html#554]
## Question or comment
I am looking to wrap an <img> tag into <a> tag. However, the documentation does seem to describe such functionality, only trimming tags. Any chance you could suggest me how it's done?
My goal is that every <img> would have a link that'd actually open that image in a new tab.

**Comment by BoDonkey** [comment]
Hi @geantas - I think this would be possible in sanitize-html, but it would probably be easier to use "cheerio" as a second step after sanitize-html. The [cheerio package](https://www.npmjs.com/package/cheerio) is likely already installed in your project and is well suited to manipulating the DOM structure on the server.

**Comment by boutell** [comment]
@BoDonkey gives good advice here. Just a quick note that `cheerio` might or might not already be present since `sanitize-html` is often used outside of ApostropheCMS, and in any case you should explicitly `npm install` anything you plan to use in your project rather than relying on sub-dependencies being present, although it's true you only pay for the space once if it's already a sub-dependency.
