### ISSUE TITLE
Build warning Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by dennisat** [apostrophecms/sanitize-html#669]
**But it is not yours! Is coming from a dependency!** and it is not urgent.

# The origin

```
WARNING in /Users/user/dev/company/project--1/node_modules/.pnpm/picocolors@1.0.1/node_modules/picocolors/picocolors.js 8:3-10
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ /Users/user/dev/company/project--1/node_modules/.pnpm/postcss@8.4.39/node_modules/postcss/lib/css-syntax-error.js
 @ /Users/user/dev/company/project--1/node_modules/.pnpm/postcss@8.4.39/node_modules/postcss/lib/postcss.js
 @ /Users/user/dev/company/project--1/node_modules/.pnpm/sanitize-html@2.13.0/node_modules/sanitize-html/index.js
 @ ../utils-library/dist/commonJs/validation-engine/utils/isSanitizedHtml.js
...
```

# Solutions

You have to bump the `postcss` when it is ready.

I would appreciate any other help.

**Comment by serhiiminin** [comment]
Hi all,
I tried to override `postcss` version on my side. It seems to be working fine with the latest `postcss` version
```json
"overrides": {
    "sanitize-html": {
        "postcss": "^8.4.40"
    }
} 
```

It would be appreciated if maintainers could update to the latest postcss version

**Comment by boutell** [comment]
The module currently depends on `^8.3.11`. Note the `^`. This means "8.3.11 or better, as long as we stay within the 8.x series." That seems correct. An "npm update" of a project containing our module will automatically get 8.4.40 or whatever the current 8.x release is. A fresh "npm install sanitize-html" in a project that doesn't have the module yet will also get 8.4.40... et cetera.

I think what you're asking us to do is bump the dependency anyway, so that "npm update sanitize-html" also updates postcss. But that's not really sanitize-html's job and it would eventually require us to make a release every time there is any update to any dependency.

This defeats the purpose of semantic versioning rules, so I think it's not a road we want to start down. Unless I'm missing something.

**Comment by serhiiminin** [comment]
@boutell, thank you for your response. I apologize, it is my mistake. For some reason, I was under the impression there was `~8.3.11` instead of `^8.3.11`

I cleaned up my npm cache and regenerated the lock file. Now it resolves to the latest version of `postcss`
<img width="265" alt="image" src="https://github.com/user-attachments/assets/36894971-0bb6-45bd-96d4-d56c0e4129c7">


Although, it does not solve the issue.
<img width="612" alt="image" src="https://github.com/user-attachments/assets/2042ca2c-ca4c-4f77-96a0-e231eb28b642">

I could only solve it by adding `postcss` as a dependency to my project
